### ISSUE TITLE
[Feature Request] Add clicking score opens MAL (or AniList)

### ISSUE THREAD

**Issue by ipkpjersi** [befabri/crunchyscore#4]
Hi,

I think it would be a really nice feature to have clicking on the score opening MAL or AniList, that way you can click the 6.05 here and then it can open up MAL so you can read more about it:
![Screenshot_2024-11-12_20-45-23](https://github.com/user-attachments/assets/041f3c1f-90e4-4301-8e17-e1fb50b42823)

Cheers.

**Comment by befabri** [comment]
Thank you for the suggestion! I agree it would be a useful feature. I initially avoided it to prevent easy retrieval of associations between Crunchyroll, MyAnimeList, and AniList through my API. However, I’ll consider implementing it.

Would you like an option to display both MAL and AniList scores? I could also add a MAL or AniList logo next to the score for clarity (as an optional feature)

**Comment by ipkpjersi** [comment]
I didn't even consider an option to display both scores, that's a fantastic idea.

I'm big on optional features, so yes everything you just said sounds great to me.

**Comment by befabri** [comment]
The feature to click on a score and open the corresponding MyAnimeList (MAL) or AniList page has been successfully implemented. However, the option to display both MAL and AniList scores simultaneously has not been added in this update. I didn’t have time but will do it soon.

**Comment by ipkpjersi** [comment]
I'm on the new update, but clicking on the score doesn't seem to be working, nothing happens when clicking on the score:
![image](https://github.com/user-attachments/assets/d0b15ce0-5ab6-4f2e-85e8-c8aeb1691c78)

**Comment by befabri** [comment]
This is expected behavior when there's no ID. The extension hasn’t updated the scores yet, so it hasn’t received the ID for it.
It works for me.
Maybe I should add a button to refresh manually if needed

**Comment by ipkpjersi** [comment]
I just had an idea, but I'm not sure that it's worth opening a separate issue for so I'll post it in here for now.

Is it worth integrating like for example MAL reviews into Crunchyroll itself via this plugin as an optional feature? I'm not sure how feasible that would be, or if it would be too much work for it to be worth it. I'd like to hear your thoughts on this since you are likely already somewhat familiar with it since you made this plugin. 

Cheers.

**Comment by befabri** [comment]
Currently, MAL doesn’t provide an API endpoint for anime reviews. While scraping reviews is technically possible, it would violate their ToS. 
However, MAL does offer an endpoint for forum topics, which could be used to access episode discussion threads.
Since the removal of the comment section, I haven't really looked at what the current extensions offer on this subject but I think it's outside the scope of the extension

**Comment by ipkpjersi** [comment]
That makes sense, thanks! That's a shame they don't provide an API endpoint for anime reviews, I think that might have been a cool feature.

**Comment by befabri** [comment]
Once I have time, I'll implement simultaneous displays of MAL and AniList scores and provide an option to display the simulcast season scores rather than just displaying the Season 1 score.
